default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: soumya
  password:

development:
  <<: *default
  database: triva-zone-development

test:
  <<: *default
  database: triva-zone-test
